#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AeronauticaMilitare
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="basemilitare")]
	public partial class DataClassesAMDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definizioni metodo Extensibility
    partial void OnCreated();
    partial void InsertAEROMOBILE(AEROMOBILE instance);
    partial void UpdateAEROMOBILE(AEROMOBILE instance);
    partial void DeleteAEROMOBILE(AEROMOBILE instance);
    partial void InsertVOLO(VOLO instance);
    partial void UpdateVOLO(VOLO instance);
    partial void DeleteVOLO(VOLO instance);
    partial void InsertAEROPORTO(AEROPORTO instance);
    partial void UpdateAEROPORTO(AEROPORTO instance);
    partial void DeleteAEROPORTO(AEROPORTO instance);
    partial void InsertARMAMENTO(ARMAMENTO instance);
    partial void UpdateARMAMENTO(ARMAMENTO instance);
    partial void DeleteARMAMENTO(ARMAMENTO instance);
    partial void InsertIDONEITA_MEDICA(IDONEITA_MEDICA instance);
    partial void UpdateIDONEITA_MEDICA(IDONEITA_MEDICA instance);
    partial void DeleteIDONEITA_MEDICA(IDONEITA_MEDICA instance);
    partial void InsertMANUTENZIONE(MANUTENZIONE instance);
    partial void UpdateMANUTENZIONE(MANUTENZIONE instance);
    partial void DeleteMANUTENZIONE(MANUTENZIONE instance);
    partial void InsertMILITARE(MILITARE instance);
    partial void UpdateMILITARE(MILITARE instance);
    partial void DeleteMILITARE(MILITARE instance);
    partial void InsertMISSIONE(MISSIONE instance);
    partial void UpdateMISSIONE(MISSIONE instance);
    partial void DeleteMISSIONE(MISSIONE instance);
    partial void InsertPATENTE(PATENTE instance);
    partial void UpdatePATENTE(PATENTE instance);
    partial void DeletePATENTE(PATENTE instance);
    #endregion
		
		public DataClassesAMDataContext() : 
				base(global::AeronauticaMilitare.Properties.Settings.Default.basemilitareConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesAMDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesAMDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesAMDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesAMDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AEROMOBILE> AEROMOBILE
		{
			get
			{
				return this.GetTable<AEROMOBILE>();
			}
		}
		
		public System.Data.Linq.Table<VOLO> VOLO
		{
			get
			{
				return this.GetTable<VOLO>();
			}
		}
		
		public System.Data.Linq.Table<AEROPORTO> AEROPORTO
		{
			get
			{
				return this.GetTable<AEROPORTO>();
			}
		}
		
		public System.Data.Linq.Table<ARMAMENTO> ARMAMENTO
		{
			get
			{
				return this.GetTable<ARMAMENTO>();
			}
		}
		
		public System.Data.Linq.Table<IDONEITA_MEDICA> IDONEITA_MEDICA
		{
			get
			{
				return this.GetTable<IDONEITA_MEDICA>();
			}
		}
		
		public System.Data.Linq.Table<MANUTENZIONE> MANUTENZIONE
		{
			get
			{
				return this.GetTable<MANUTENZIONE>();
			}
		}
		
		public System.Data.Linq.Table<MILITARE> MILITARE
		{
			get
			{
				return this.GetTable<MILITARE>();
			}
		}
		
		public System.Data.Linq.Table<MISSIONE> MISSIONE
		{
			get
			{
				return this.GetTable<MISSIONE>();
			}
		}
		
		public System.Data.Linq.Table<PATENTE> PATENTE
		{
			get
			{
				return this.GetTable<PATENTE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AEROMOBILE")]
	public partial class AEROMOBILE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodiceAeromobile;
		
		private string _Nome;
		
		private string _Costruttore;
		
		private string _FunzionePrimaria;
		
		private float _QuotaOperativa;
		
		private float _VelocitàMassima;
		
		private float _Autonomia;
		
		private float _SpintaMassima;
		
		private float _CapienzaSerbatoio;
		
		private string _Motore;
		
		private float _Peso;
		
		private float _LunghezzaPistaDiAtterraggio;
		
		private int _NumeroMembri;
		
		private string _Dimensioni;
		
		private EntitySet<VOLO> _VOLO;
		
		private EntitySet<ARMAMENTO> _ARMAMENTO;
		
		private EntitySet<MANUTENZIONE> _MANUTENZIONE;
		
		private EntitySet<PATENTE> _PATENTE;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodiceAeromobileChanging(string value);
    partial void OnCodiceAeromobileChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnCostruttoreChanging(string value);
    partial void OnCostruttoreChanged();
    partial void OnFunzionePrimariaChanging(string value);
    partial void OnFunzionePrimariaChanged();
    partial void OnQuotaOperativaChanging(float value);
    partial void OnQuotaOperativaChanged();
    partial void OnVelocitàMassimaChanging(float value);
    partial void OnVelocitàMassimaChanged();
    partial void OnAutonomiaChanging(float value);
    partial void OnAutonomiaChanged();
    partial void OnSpintaMassimaChanging(float value);
    partial void OnSpintaMassimaChanged();
    partial void OnCapienzaSerbatoioChanging(float value);
    partial void OnCapienzaSerbatoioChanged();
    partial void OnMotoreChanging(string value);
    partial void OnMotoreChanged();
    partial void OnPesoChanging(float value);
    partial void OnPesoChanged();
    partial void OnLunghezzaPistaDiAtterraggioChanging(float value);
    partial void OnLunghezzaPistaDiAtterraggioChanged();
    partial void OnNumeroMembriChanging(int value);
    partial void OnNumeroMembriChanged();
    partial void OnDimensioniChanging(string value);
    partial void OnDimensioniChanged();
    #endregion
		
		public AEROMOBILE()
		{
			this._VOLO = new EntitySet<VOLO>(new Action<VOLO>(this.attach_VOLO), new Action<VOLO>(this.detach_VOLO));
			this._ARMAMENTO = new EntitySet<ARMAMENTO>(new Action<ARMAMENTO>(this.attach_ARMAMENTO), new Action<ARMAMENTO>(this.detach_ARMAMENTO));
			this._MANUTENZIONE = new EntitySet<MANUTENZIONE>(new Action<MANUTENZIONE>(this.attach_MANUTENZIONE), new Action<MANUTENZIONE>(this.detach_MANUTENZIONE));
			this._PATENTE = new EntitySet<PATENTE>(new Action<PATENTE>(this.attach_PATENTE), new Action<PATENTE>(this.detach_PATENTE));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceAeromobile", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodiceAeromobile
		{
			get
			{
				return this._CodiceAeromobile;
			}
			set
			{
				if ((this._CodiceAeromobile != value))
				{
					this.OnCodiceAeromobileChanging(value);
					this.SendPropertyChanging();
					this._CodiceAeromobile = value;
					this.SendPropertyChanged("CodiceAeromobile");
					this.OnCodiceAeromobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Costruttore", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Costruttore
		{
			get
			{
				return this._Costruttore;
			}
			set
			{
				if ((this._Costruttore != value))
				{
					this.OnCostruttoreChanging(value);
					this.SendPropertyChanging();
					this._Costruttore = value;
					this.SendPropertyChanged("Costruttore");
					this.OnCostruttoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FunzionePrimaria", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string FunzionePrimaria
		{
			get
			{
				return this._FunzionePrimaria;
			}
			set
			{
				if ((this._FunzionePrimaria != value))
				{
					this.OnFunzionePrimariaChanging(value);
					this.SendPropertyChanging();
					this._FunzionePrimaria = value;
					this.SendPropertyChanged("FunzionePrimaria");
					this.OnFunzionePrimariaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuotaOperativa", DbType="Real NOT NULL")]
		public float QuotaOperativa
		{
			get
			{
				return this._QuotaOperativa;
			}
			set
			{
				if ((this._QuotaOperativa != value))
				{
					this.OnQuotaOperativaChanging(value);
					this.SendPropertyChanging();
					this._QuotaOperativa = value;
					this.SendPropertyChanged("QuotaOperativa");
					this.OnQuotaOperativaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VelocitàMassima", DbType="Real NOT NULL")]
		public float VelocitàMassima
		{
			get
			{
				return this._VelocitàMassima;
			}
			set
			{
				if ((this._VelocitàMassima != value))
				{
					this.OnVelocitàMassimaChanging(value);
					this.SendPropertyChanging();
					this._VelocitàMassima = value;
					this.SendPropertyChanged("VelocitàMassima");
					this.OnVelocitàMassimaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Autonomia", DbType="Real NOT NULL")]
		public float Autonomia
		{
			get
			{
				return this._Autonomia;
			}
			set
			{
				if ((this._Autonomia != value))
				{
					this.OnAutonomiaChanging(value);
					this.SendPropertyChanging();
					this._Autonomia = value;
					this.SendPropertyChanged("Autonomia");
					this.OnAutonomiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpintaMassima", DbType="Real NOT NULL")]
		public float SpintaMassima
		{
			get
			{
				return this._SpintaMassima;
			}
			set
			{
				if ((this._SpintaMassima != value))
				{
					this.OnSpintaMassimaChanging(value);
					this.SendPropertyChanging();
					this._SpintaMassima = value;
					this.SendPropertyChanged("SpintaMassima");
					this.OnSpintaMassimaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapienzaSerbatoio", DbType="Real NOT NULL")]
		public float CapienzaSerbatoio
		{
			get
			{
				return this._CapienzaSerbatoio;
			}
			set
			{
				if ((this._CapienzaSerbatoio != value))
				{
					this.OnCapienzaSerbatoioChanging(value);
					this.SendPropertyChanging();
					this._CapienzaSerbatoio = value;
					this.SendPropertyChanged("CapienzaSerbatoio");
					this.OnCapienzaSerbatoioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Motore", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Motore
		{
			get
			{
				return this._Motore;
			}
			set
			{
				if ((this._Motore != value))
				{
					this.OnMotoreChanging(value);
					this.SendPropertyChanging();
					this._Motore = value;
					this.SendPropertyChanged("Motore");
					this.OnMotoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Peso", DbType="Real NOT NULL")]
		public float Peso
		{
			get
			{
				return this._Peso;
			}
			set
			{
				if ((this._Peso != value))
				{
					this.OnPesoChanging(value);
					this.SendPropertyChanging();
					this._Peso = value;
					this.SendPropertyChanged("Peso");
					this.OnPesoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LunghezzaPistaDiAtterraggio", DbType="Real NOT NULL")]
		public float LunghezzaPistaDiAtterraggio
		{
			get
			{
				return this._LunghezzaPistaDiAtterraggio;
			}
			set
			{
				if ((this._LunghezzaPistaDiAtterraggio != value))
				{
					this.OnLunghezzaPistaDiAtterraggioChanging(value);
					this.SendPropertyChanging();
					this._LunghezzaPistaDiAtterraggio = value;
					this.SendPropertyChanged("LunghezzaPistaDiAtterraggio");
					this.OnLunghezzaPistaDiAtterraggioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroMembri", DbType="Int NOT NULL")]
		public int NumeroMembri
		{
			get
			{
				return this._NumeroMembri;
			}
			set
			{
				if ((this._NumeroMembri != value))
				{
					this.OnNumeroMembriChanging(value);
					this.SendPropertyChanging();
					this._NumeroMembri = value;
					this.SendPropertyChanged("NumeroMembri");
					this.OnNumeroMembriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dimensioni", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Dimensioni
		{
			get
			{
				return this._Dimensioni;
			}
			set
			{
				if ((this._Dimensioni != value))
				{
					this.OnDimensioniChanging(value);
					this.SendPropertyChanging();
					this._Dimensioni = value;
					this.SendPropertyChanged("Dimensioni");
					this.OnDimensioniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AEROMOBILE_VOLO", Storage="_VOLO", ThisKey="CodiceAeromobile", OtherKey="CodiceAeromobile")]
		public EntitySet<VOLO> VOLO
		{
			get
			{
				return this._VOLO;
			}
			set
			{
				this._VOLO.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AEROMOBILE_ARMAMENTO", Storage="_ARMAMENTO", ThisKey="CodiceAeromobile", OtherKey="CodiceAeromobile")]
		public EntitySet<ARMAMENTO> ARMAMENTO
		{
			get
			{
				return this._ARMAMENTO;
			}
			set
			{
				this._ARMAMENTO.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AEROMOBILE_MANUTENZIONE", Storage="_MANUTENZIONE", ThisKey="CodiceAeromobile", OtherKey="CodiceAeromobile")]
		public EntitySet<MANUTENZIONE> MANUTENZIONE
		{
			get
			{
				return this._MANUTENZIONE;
			}
			set
			{
				this._MANUTENZIONE.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AEROMOBILE_PATENTE", Storage="_PATENTE", ThisKey="CodiceAeromobile", OtherKey="CodiceAeromobile")]
		public EntitySet<PATENTE> PATENTE
		{
			get
			{
				return this._PATENTE;
			}
			set
			{
				this._PATENTE.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VOLO(VOLO entity)
		{
			this.SendPropertyChanging();
			entity.AEROMOBILE = this;
		}
		
		private void detach_VOLO(VOLO entity)
		{
			this.SendPropertyChanging();
			entity.AEROMOBILE = null;
		}
		
		private void attach_ARMAMENTO(ARMAMENTO entity)
		{
			this.SendPropertyChanging();
			entity.AEROMOBILE = this;
		}
		
		private void detach_ARMAMENTO(ARMAMENTO entity)
		{
			this.SendPropertyChanging();
			entity.AEROMOBILE = null;
		}
		
		private void attach_MANUTENZIONE(MANUTENZIONE entity)
		{
			this.SendPropertyChanging();
			entity.AEROMOBILE = this;
		}
		
		private void detach_MANUTENZIONE(MANUTENZIONE entity)
		{
			this.SendPropertyChanging();
			entity.AEROMOBILE = null;
		}
		
		private void attach_PATENTE(PATENTE entity)
		{
			this.SendPropertyChanging();
			entity.AEROMOBILE = this;
		}
		
		private void detach_PATENTE(PATENTE entity)
		{
			this.SendPropertyChanging();
			entity.AEROMOBILE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VOLO")]
	public partial class VOLO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodiceVolo;
		
		private float _Partenza;
		
		private float _Arrivo;
		
		private System.DateTime _Data;
		
		private int _DurataComplessiva;
		
		private string _MatricolaMilitare;
		
		private string _CodiceAeromobile;
		
		private string _Nome;
		
		private EntityRef<AEROMOBILE> _AEROMOBILE;
		
		private EntityRef<MILITARE> _MILITARE;
		
		private EntityRef<MISSIONE> _MISSIONE;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodiceVoloChanging(string value);
    partial void OnCodiceVoloChanged();
    partial void OnPartenzaChanging(float value);
    partial void OnPartenzaChanged();
    partial void OnArrivoChanging(float value);
    partial void OnArrivoChanged();
    partial void OnDataChanging(System.DateTime value);
    partial void OnDataChanged();
    partial void OnDurataComplessivaChanging(int value);
    partial void OnDurataComplessivaChanged();
    partial void OnMatricolaMilitareChanging(string value);
    partial void OnMatricolaMilitareChanged();
    partial void OnCodiceAeromobileChanging(string value);
    partial void OnCodiceAeromobileChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    #endregion
		
		public VOLO()
		{
			this._AEROMOBILE = default(EntityRef<AEROMOBILE>);
			this._MILITARE = default(EntityRef<MILITARE>);
			this._MISSIONE = default(EntityRef<MISSIONE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceVolo", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodiceVolo
		{
			get
			{
				return this._CodiceVolo;
			}
			set
			{
				if ((this._CodiceVolo != value))
				{
					this.OnCodiceVoloChanging(value);
					this.SendPropertyChanging();
					this._CodiceVolo = value;
					this.SendPropertyChanged("CodiceVolo");
					this.OnCodiceVoloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Partenza", DbType="Real NOT NULL")]
		public float Partenza
		{
			get
			{
				return this._Partenza;
			}
			set
			{
				if ((this._Partenza != value))
				{
					this.OnPartenzaChanging(value);
					this.SendPropertyChanging();
					this._Partenza = value;
					this.SendPropertyChanged("Partenza");
					this.OnPartenzaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Arrivo", DbType="Real NOT NULL")]
		public float Arrivo
		{
			get
			{
				return this._Arrivo;
			}
			set
			{
				if ((this._Arrivo != value))
				{
					this.OnArrivoChanging(value);
					this.SendPropertyChanging();
					this._Arrivo = value;
					this.SendPropertyChanged("Arrivo");
					this.OnArrivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="Date NOT NULL")]
		public System.DateTime Data
		{
			get
			{
				return this._Data;
			}
			set
			{
				if ((this._Data != value))
				{
					this.OnDataChanging(value);
					this.SendPropertyChanging();
					this._Data = value;
					this.SendPropertyChanged("Data");
					this.OnDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DurataComplessiva", DbType="Int NOT NULL")]
		public int DurataComplessiva
		{
			get
			{
				return this._DurataComplessiva;
			}
			set
			{
				if ((this._DurataComplessiva != value))
				{
					this.OnDurataComplessivaChanging(value);
					this.SendPropertyChanging();
					this._DurataComplessiva = value;
					this.SendPropertyChanged("DurataComplessiva");
					this.OnDurataComplessivaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatricolaMilitare", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string MatricolaMilitare
		{
			get
			{
				return this._MatricolaMilitare;
			}
			set
			{
				if ((this._MatricolaMilitare != value))
				{
					if (this._MILITARE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMatricolaMilitareChanging(value);
					this.SendPropertyChanging();
					this._MatricolaMilitare = value;
					this.SendPropertyChanged("MatricolaMilitare");
					this.OnMatricolaMilitareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceAeromobile", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string CodiceAeromobile
		{
			get
			{
				return this._CodiceAeromobile;
			}
			set
			{
				if ((this._CodiceAeromobile != value))
				{
					if (this._AEROMOBILE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodiceAeromobileChanging(value);
					this.SendPropertyChanging();
					this._CodiceAeromobile = value;
					this.SendPropertyChanged("CodiceAeromobile");
					this.OnCodiceAeromobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					if (this._MISSIONE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AEROMOBILE_VOLO", Storage="_AEROMOBILE", ThisKey="CodiceAeromobile", OtherKey="CodiceAeromobile", IsForeignKey=true)]
		public AEROMOBILE AEROMOBILE
		{
			get
			{
				return this._AEROMOBILE.Entity;
			}
			set
			{
				AEROMOBILE previousValue = this._AEROMOBILE.Entity;
				if (((previousValue != value) 
							|| (this._AEROMOBILE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AEROMOBILE.Entity = null;
						previousValue.VOLO.Remove(this);
					}
					this._AEROMOBILE.Entity = value;
					if ((value != null))
					{
						value.VOLO.Add(this);
						this._CodiceAeromobile = value.CodiceAeromobile;
					}
					else
					{
						this._CodiceAeromobile = default(string);
					}
					this.SendPropertyChanged("AEROMOBILE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MILITARE_VOLO", Storage="_MILITARE", ThisKey="MatricolaMilitare", OtherKey="MatricolaMilitare", IsForeignKey=true)]
		public MILITARE MILITARE
		{
			get
			{
				return this._MILITARE.Entity;
			}
			set
			{
				MILITARE previousValue = this._MILITARE.Entity;
				if (((previousValue != value) 
							|| (this._MILITARE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MILITARE.Entity = null;
						previousValue.VOLO.Remove(this);
					}
					this._MILITARE.Entity = value;
					if ((value != null))
					{
						value.VOLO.Add(this);
						this._MatricolaMilitare = value.MatricolaMilitare;
					}
					else
					{
						this._MatricolaMilitare = default(string);
					}
					this.SendPropertyChanged("MILITARE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MISSIONE_VOLO", Storage="_MISSIONE", ThisKey="Nome", OtherKey="Nome", IsForeignKey=true)]
		public MISSIONE MISSIONE
		{
			get
			{
				return this._MISSIONE.Entity;
			}
			set
			{
				MISSIONE previousValue = this._MISSIONE.Entity;
				if (((previousValue != value) 
							|| (this._MISSIONE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MISSIONE.Entity = null;
						previousValue.VOLO.Remove(this);
					}
					this._MISSIONE.Entity = value;
					if ((value != null))
					{
						value.VOLO.Add(this);
						this._Nome = value.Nome;
					}
					else
					{
						this._Nome = default(string);
					}
					this.SendPropertyChanged("MISSIONE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AEROPORTO")]
	public partial class AEROPORTO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodiceAeroporto;
		
		private float _LunghezzaPista;
		
		private EntitySet<MISSIONE> _MISSIONE;
		
		private EntitySet<MISSIONE> _MISSIONE1;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodiceAeroportoChanging(string value);
    partial void OnCodiceAeroportoChanged();
    partial void OnLunghezzaPistaChanging(float value);
    partial void OnLunghezzaPistaChanged();
    #endregion
		
		public AEROPORTO()
		{
			this._MISSIONE = new EntitySet<MISSIONE>(new Action<MISSIONE>(this.attach_MISSIONE), new Action<MISSIONE>(this.detach_MISSIONE));
			this._MISSIONE1 = new EntitySet<MISSIONE>(new Action<MISSIONE>(this.attach_MISSIONE1), new Action<MISSIONE>(this.detach_MISSIONE1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceAeroporto", DbType="VarChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodiceAeroporto
		{
			get
			{
				return this._CodiceAeroporto;
			}
			set
			{
				if ((this._CodiceAeroporto != value))
				{
					this.OnCodiceAeroportoChanging(value);
					this.SendPropertyChanging();
					this._CodiceAeroporto = value;
					this.SendPropertyChanged("CodiceAeroporto");
					this.OnCodiceAeroportoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LunghezzaPista", DbType="Real NOT NULL")]
		public float LunghezzaPista
		{
			get
			{
				return this._LunghezzaPista;
			}
			set
			{
				if ((this._LunghezzaPista != value))
				{
					this.OnLunghezzaPistaChanging(value);
					this.SendPropertyChanging();
					this._LunghezzaPista = value;
					this.SendPropertyChanged("LunghezzaPista");
					this.OnLunghezzaPistaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AEROPORTO_MISSIONE", Storage="_MISSIONE", ThisKey="CodiceAeroporto", OtherKey="AeroportoDiArrivo")]
		public EntitySet<MISSIONE> MISSIONE
		{
			get
			{
				return this._MISSIONE;
			}
			set
			{
				this._MISSIONE.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AEROPORTO_MISSIONE1", Storage="_MISSIONE1", ThisKey="CodiceAeroporto", OtherKey="AeroportoDiPartenza")]
		public EntitySet<MISSIONE> MISSIONE1
		{
			get
			{
				return this._MISSIONE1;
			}
			set
			{
				this._MISSIONE1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MISSIONE(MISSIONE entity)
		{
			this.SendPropertyChanging();
			entity.AEROPORTO = this;
		}
		
		private void detach_MISSIONE(MISSIONE entity)
		{
			this.SendPropertyChanging();
			entity.AEROPORTO = null;
		}
		
		private void attach_MISSIONE1(MISSIONE entity)
		{
			this.SendPropertyChanging();
			entity.AEROPORTO1 = this;
		}
		
		private void detach_MISSIONE1(MISSIONE entity)
		{
			this.SendPropertyChanging();
			entity.AEROPORTO1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ARMAMENTO")]
	public partial class ARMAMENTO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodiceAeromobile;
		
		private string _CodiceArmamento;
		
		private int _NumeroMissili;
		
		private int _NumeroMunizioni;
		
		private EntityRef<AEROMOBILE> _AEROMOBILE;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodiceAeromobileChanging(string value);
    partial void OnCodiceAeromobileChanged();
    partial void OnCodiceArmamentoChanging(string value);
    partial void OnCodiceArmamentoChanged();
    partial void OnNumeroMissiliChanging(int value);
    partial void OnNumeroMissiliChanged();
    partial void OnNumeroMunizioniChanging(int value);
    partial void OnNumeroMunizioniChanged();
    #endregion
		
		public ARMAMENTO()
		{
			this._AEROMOBILE = default(EntityRef<AEROMOBILE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceAeromobile", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodiceAeromobile
		{
			get
			{
				return this._CodiceAeromobile;
			}
			set
			{
				if ((this._CodiceAeromobile != value))
				{
					if (this._AEROMOBILE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodiceAeromobileChanging(value);
					this.SendPropertyChanging();
					this._CodiceAeromobile = value;
					this.SendPropertyChanged("CodiceAeromobile");
					this.OnCodiceAeromobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceArmamento", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodiceArmamento
		{
			get
			{
				return this._CodiceArmamento;
			}
			set
			{
				if ((this._CodiceArmamento != value))
				{
					this.OnCodiceArmamentoChanging(value);
					this.SendPropertyChanging();
					this._CodiceArmamento = value;
					this.SendPropertyChanged("CodiceArmamento");
					this.OnCodiceArmamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroMissili", DbType="Int NOT NULL")]
		public int NumeroMissili
		{
			get
			{
				return this._NumeroMissili;
			}
			set
			{
				if ((this._NumeroMissili != value))
				{
					this.OnNumeroMissiliChanging(value);
					this.SendPropertyChanging();
					this._NumeroMissili = value;
					this.SendPropertyChanged("NumeroMissili");
					this.OnNumeroMissiliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroMunizioni", DbType="Int NOT NULL")]
		public int NumeroMunizioni
		{
			get
			{
				return this._NumeroMunizioni;
			}
			set
			{
				if ((this._NumeroMunizioni != value))
				{
					this.OnNumeroMunizioniChanging(value);
					this.SendPropertyChanging();
					this._NumeroMunizioni = value;
					this.SendPropertyChanged("NumeroMunizioni");
					this.OnNumeroMunizioniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AEROMOBILE_ARMAMENTO", Storage="_AEROMOBILE", ThisKey="CodiceAeromobile", OtherKey="CodiceAeromobile", IsForeignKey=true)]
		public AEROMOBILE AEROMOBILE
		{
			get
			{
				return this._AEROMOBILE.Entity;
			}
			set
			{
				AEROMOBILE previousValue = this._AEROMOBILE.Entity;
				if (((previousValue != value) 
							|| (this._AEROMOBILE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AEROMOBILE.Entity = null;
						previousValue.ARMAMENTO.Remove(this);
					}
					this._AEROMOBILE.Entity = value;
					if ((value != null))
					{
						value.ARMAMENTO.Add(this);
						this._CodiceAeromobile = value.CodiceAeromobile;
					}
					else
					{
						this._CodiceAeromobile = default(string);
					}
					this.SendPropertyChanged("AEROMOBILE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IDONEITA_MEDICA")]
	public partial class IDONEITA_MEDICA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodiceIdoneità;
		
		private bool _StatoMentale;
		
		private bool _CondizioniGenerali;
		
		private System.DateTime _DataDiScadenza;
		
		private string _MatricolaMilitare;
		
		private EntityRef<MILITARE> _MILITARE;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodiceIdoneitàChanging(string value);
    partial void OnCodiceIdoneitàChanged();
    partial void OnStatoMentaleChanging(bool value);
    partial void OnStatoMentaleChanged();
    partial void OnCondizioniGeneraliChanging(bool value);
    partial void OnCondizioniGeneraliChanged();
    partial void OnDataDiScadenzaChanging(System.DateTime value);
    partial void OnDataDiScadenzaChanged();
    partial void OnMatricolaMilitareChanging(string value);
    partial void OnMatricolaMilitareChanged();
    #endregion
		
		public IDONEITA_MEDICA()
		{
			this._MILITARE = default(EntityRef<MILITARE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceIdoneità", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodiceIdoneità
		{
			get
			{
				return this._CodiceIdoneità;
			}
			set
			{
				if ((this._CodiceIdoneità != value))
				{
					this.OnCodiceIdoneitàChanging(value);
					this.SendPropertyChanging();
					this._CodiceIdoneità = value;
					this.SendPropertyChanged("CodiceIdoneità");
					this.OnCodiceIdoneitàChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatoMentale", DbType="Bit NOT NULL")]
		public bool StatoMentale
		{
			get
			{
				return this._StatoMentale;
			}
			set
			{
				if ((this._StatoMentale != value))
				{
					this.OnStatoMentaleChanging(value);
					this.SendPropertyChanging();
					this._StatoMentale = value;
					this.SendPropertyChanged("StatoMentale");
					this.OnStatoMentaleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CondizioniGenerali", DbType="Bit NOT NULL")]
		public bool CondizioniGenerali
		{
			get
			{
				return this._CondizioniGenerali;
			}
			set
			{
				if ((this._CondizioniGenerali != value))
				{
					this.OnCondizioniGeneraliChanging(value);
					this.SendPropertyChanging();
					this._CondizioniGenerali = value;
					this.SendPropertyChanged("CondizioniGenerali");
					this.OnCondizioniGeneraliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataDiScadenza", DbType="Date NOT NULL")]
		public System.DateTime DataDiScadenza
		{
			get
			{
				return this._DataDiScadenza;
			}
			set
			{
				if ((this._DataDiScadenza != value))
				{
					this.OnDataDiScadenzaChanging(value);
					this.SendPropertyChanging();
					this._DataDiScadenza = value;
					this.SendPropertyChanged("DataDiScadenza");
					this.OnDataDiScadenzaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatricolaMilitare", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string MatricolaMilitare
		{
			get
			{
				return this._MatricolaMilitare;
			}
			set
			{
				if ((this._MatricolaMilitare != value))
				{
					if (this._MILITARE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMatricolaMilitareChanging(value);
					this.SendPropertyChanging();
					this._MatricolaMilitare = value;
					this.SendPropertyChanged("MatricolaMilitare");
					this.OnMatricolaMilitareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MILITARE_IDONEITA_MEDICA", Storage="_MILITARE", ThisKey="MatricolaMilitare", OtherKey="MatricolaMilitare", IsForeignKey=true)]
		public MILITARE MILITARE
		{
			get
			{
				return this._MILITARE.Entity;
			}
			set
			{
				MILITARE previousValue = this._MILITARE.Entity;
				if (((previousValue != value) 
							|| (this._MILITARE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MILITARE.Entity = null;
						previousValue.IDONEITA_MEDICA.Remove(this);
					}
					this._MILITARE.Entity = value;
					if ((value != null))
					{
						value.IDONEITA_MEDICA.Add(this);
						this._MatricolaMilitare = value.MatricolaMilitare;
					}
					else
					{
						this._MatricolaMilitare = default(string);
					}
					this.SendPropertyChanged("MILITARE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MANUTENZIONE")]
	public partial class MANUTENZIONE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodiceAeromobile;
		
		private string _MatricolaMilitare;
		
		private System.DateTime _Data;
		
		private bool _StatoDelVelivolo;
		
		private EntityRef<AEROMOBILE> _AEROMOBILE;
		
		private EntityRef<MILITARE> _MILITARE;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodiceAeromobileChanging(string value);
    partial void OnCodiceAeromobileChanged();
    partial void OnMatricolaMilitareChanging(string value);
    partial void OnMatricolaMilitareChanged();
    partial void OnDataChanging(System.DateTime value);
    partial void OnDataChanged();
    partial void OnStatoDelVelivoloChanging(bool value);
    partial void OnStatoDelVelivoloChanged();
    #endregion
		
		public MANUTENZIONE()
		{
			this._AEROMOBILE = default(EntityRef<AEROMOBILE>);
			this._MILITARE = default(EntityRef<MILITARE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceAeromobile", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodiceAeromobile
		{
			get
			{
				return this._CodiceAeromobile;
			}
			set
			{
				if ((this._CodiceAeromobile != value))
				{
					if (this._AEROMOBILE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodiceAeromobileChanging(value);
					this.SendPropertyChanging();
					this._CodiceAeromobile = value;
					this.SendPropertyChanged("CodiceAeromobile");
					this.OnCodiceAeromobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatricolaMilitare", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MatricolaMilitare
		{
			get
			{
				return this._MatricolaMilitare;
			}
			set
			{
				if ((this._MatricolaMilitare != value))
				{
					if (this._MILITARE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMatricolaMilitareChanging(value);
					this.SendPropertyChanging();
					this._MatricolaMilitare = value;
					this.SendPropertyChanged("MatricolaMilitare");
					this.OnMatricolaMilitareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime Data
		{
			get
			{
				return this._Data;
			}
			set
			{
				if ((this._Data != value))
				{
					this.OnDataChanging(value);
					this.SendPropertyChanging();
					this._Data = value;
					this.SendPropertyChanged("Data");
					this.OnDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatoDelVelivolo", DbType="Bit NOT NULL")]
		public bool StatoDelVelivolo
		{
			get
			{
				return this._StatoDelVelivolo;
			}
			set
			{
				if ((this._StatoDelVelivolo != value))
				{
					this.OnStatoDelVelivoloChanging(value);
					this.SendPropertyChanging();
					this._StatoDelVelivolo = value;
					this.SendPropertyChanged("StatoDelVelivolo");
					this.OnStatoDelVelivoloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AEROMOBILE_MANUTENZIONE", Storage="_AEROMOBILE", ThisKey="CodiceAeromobile", OtherKey="CodiceAeromobile", IsForeignKey=true)]
		public AEROMOBILE AEROMOBILE
		{
			get
			{
				return this._AEROMOBILE.Entity;
			}
			set
			{
				AEROMOBILE previousValue = this._AEROMOBILE.Entity;
				if (((previousValue != value) 
							|| (this._AEROMOBILE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AEROMOBILE.Entity = null;
						previousValue.MANUTENZIONE.Remove(this);
					}
					this._AEROMOBILE.Entity = value;
					if ((value != null))
					{
						value.MANUTENZIONE.Add(this);
						this._CodiceAeromobile = value.CodiceAeromobile;
					}
					else
					{
						this._CodiceAeromobile = default(string);
					}
					this.SendPropertyChanged("AEROMOBILE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MILITARE_MANUTENZIONE", Storage="_MILITARE", ThisKey="MatricolaMilitare", OtherKey="MatricolaMilitare", IsForeignKey=true)]
		public MILITARE MILITARE
		{
			get
			{
				return this._MILITARE.Entity;
			}
			set
			{
				MILITARE previousValue = this._MILITARE.Entity;
				if (((previousValue != value) 
							|| (this._MILITARE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MILITARE.Entity = null;
						previousValue.MANUTENZIONE.Remove(this);
					}
					this._MILITARE.Entity = value;
					if ((value != null))
					{
						value.MANUTENZIONE.Add(this);
						this._MatricolaMilitare = value.MatricolaMilitare;
					}
					else
					{
						this._MatricolaMilitare = default(string);
					}
					this.SendPropertyChanged("MILITARE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MILITARE")]
	public partial class MILITARE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MatricolaMilitare;
		
		private string _Nome;
		
		private string _Cognome;
		
		private string _Grado;
		
		private string _Email;
		
		private string _Telefono;
		
		private string _CodiceFiscale;
		
		private string _StatoFamiliare;
		
		private string _Tipo;
		
		private System.Nullable<int> _Stormo;
		
		private System.Nullable<int> _GruppoDiVolo;
		
		private EntitySet<VOLO> _VOLO;
		
		private EntitySet<IDONEITA_MEDICA> _IDONEITA_MEDICA;
		
		private EntitySet<MANUTENZIONE> _MANUTENZIONE;
		
		private EntitySet<PATENTE> _PATENTE;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMatricolaMilitareChanging(string value);
    partial void OnMatricolaMilitareChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnCognomeChanging(string value);
    partial void OnCognomeChanged();
    partial void OnGradoChanging(string value);
    partial void OnGradoChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnCodiceFiscaleChanging(string value);
    partial void OnCodiceFiscaleChanged();
    partial void OnStatoFamiliareChanging(string value);
    partial void OnStatoFamiliareChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    partial void OnStormoChanging(System.Nullable<int> value);
    partial void OnStormoChanged();
    partial void OnGruppoDiVoloChanging(System.Nullable<int> value);
    partial void OnGruppoDiVoloChanged();
    #endregion
		
		public MILITARE()
		{
			this._VOLO = new EntitySet<VOLO>(new Action<VOLO>(this.attach_VOLO), new Action<VOLO>(this.detach_VOLO));
			this._IDONEITA_MEDICA = new EntitySet<IDONEITA_MEDICA>(new Action<IDONEITA_MEDICA>(this.attach_IDONEITA_MEDICA), new Action<IDONEITA_MEDICA>(this.detach_IDONEITA_MEDICA));
			this._MANUTENZIONE = new EntitySet<MANUTENZIONE>(new Action<MANUTENZIONE>(this.attach_MANUTENZIONE), new Action<MANUTENZIONE>(this.detach_MANUTENZIONE));
			this._PATENTE = new EntitySet<PATENTE>(new Action<PATENTE>(this.attach_PATENTE), new Action<PATENTE>(this.detach_PATENTE));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatricolaMilitare", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MatricolaMilitare
		{
			get
			{
				return this._MatricolaMilitare;
			}
			set
			{
				if ((this._MatricolaMilitare != value))
				{
					this.OnMatricolaMilitareChanging(value);
					this.SendPropertyChanging();
					this._MatricolaMilitare = value;
					this.SendPropertyChanged("MatricolaMilitare");
					this.OnMatricolaMilitareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cognome", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Cognome
		{
			get
			{
				return this._Cognome;
			}
			set
			{
				if ((this._Cognome != value))
				{
					this.OnCognomeChanging(value);
					this.SendPropertyChanging();
					this._Cognome = value;
					this.SendPropertyChanged("Cognome");
					this.OnCognomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grado", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Grado
		{
			get
			{
				return this._Grado;
			}
			set
			{
				if ((this._Grado != value))
				{
					this.OnGradoChanging(value);
					this.SendPropertyChanging();
					this._Grado = value;
					this.SendPropertyChanged("Grado");
					this.OnGradoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(13) NOT NULL", CanBeNull=false)]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceFiscale", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string CodiceFiscale
		{
			get
			{
				return this._CodiceFiscale;
			}
			set
			{
				if ((this._CodiceFiscale != value))
				{
					this.OnCodiceFiscaleChanging(value);
					this.SendPropertyChanging();
					this._CodiceFiscale = value;
					this.SendPropertyChanged("CodiceFiscale");
					this.OnCodiceFiscaleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatoFamiliare", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string StatoFamiliare
		{
			get
			{
				return this._StatoFamiliare;
			}
			set
			{
				if ((this._StatoFamiliare != value))
				{
					this.OnStatoFamiliareChanging(value);
					this.SendPropertyChanging();
					this._StatoFamiliare = value;
					this.SendPropertyChanged("StatoFamiliare");
					this.OnStatoFamiliareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stormo", DbType="Int")]
		public System.Nullable<int> Stormo
		{
			get
			{
				return this._Stormo;
			}
			set
			{
				if ((this._Stormo != value))
				{
					this.OnStormoChanging(value);
					this.SendPropertyChanging();
					this._Stormo = value;
					this.SendPropertyChanged("Stormo");
					this.OnStormoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GruppoDiVolo", DbType="Int")]
		public System.Nullable<int> GruppoDiVolo
		{
			get
			{
				return this._GruppoDiVolo;
			}
			set
			{
				if ((this._GruppoDiVolo != value))
				{
					this.OnGruppoDiVoloChanging(value);
					this.SendPropertyChanging();
					this._GruppoDiVolo = value;
					this.SendPropertyChanged("GruppoDiVolo");
					this.OnGruppoDiVoloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MILITARE_VOLO", Storage="_VOLO", ThisKey="MatricolaMilitare", OtherKey="MatricolaMilitare")]
		public EntitySet<VOLO> VOLO
		{
			get
			{
				return this._VOLO;
			}
			set
			{
				this._VOLO.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MILITARE_IDONEITA_MEDICA", Storage="_IDONEITA_MEDICA", ThisKey="MatricolaMilitare", OtherKey="MatricolaMilitare")]
		public EntitySet<IDONEITA_MEDICA> IDONEITA_MEDICA
		{
			get
			{
				return this._IDONEITA_MEDICA;
			}
			set
			{
				this._IDONEITA_MEDICA.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MILITARE_MANUTENZIONE", Storage="_MANUTENZIONE", ThisKey="MatricolaMilitare", OtherKey="MatricolaMilitare")]
		public EntitySet<MANUTENZIONE> MANUTENZIONE
		{
			get
			{
				return this._MANUTENZIONE;
			}
			set
			{
				this._MANUTENZIONE.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MILITARE_PATENTE", Storage="_PATENTE", ThisKey="MatricolaMilitare", OtherKey="MatricolaMilitare")]
		public EntitySet<PATENTE> PATENTE
		{
			get
			{
				return this._PATENTE;
			}
			set
			{
				this._PATENTE.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VOLO(VOLO entity)
		{
			this.SendPropertyChanging();
			entity.MILITARE = this;
		}
		
		private void detach_VOLO(VOLO entity)
		{
			this.SendPropertyChanging();
			entity.MILITARE = null;
		}
		
		private void attach_IDONEITA_MEDICA(IDONEITA_MEDICA entity)
		{
			this.SendPropertyChanging();
			entity.MILITARE = this;
		}
		
		private void detach_IDONEITA_MEDICA(IDONEITA_MEDICA entity)
		{
			this.SendPropertyChanging();
			entity.MILITARE = null;
		}
		
		private void attach_MANUTENZIONE(MANUTENZIONE entity)
		{
			this.SendPropertyChanging();
			entity.MILITARE = this;
		}
		
		private void detach_MANUTENZIONE(MANUTENZIONE entity)
		{
			this.SendPropertyChanging();
			entity.MILITARE = null;
		}
		
		private void attach_PATENTE(PATENTE entity)
		{
			this.SendPropertyChanging();
			entity.MILITARE = this;
		}
		
		private void detach_PATENTE(PATENTE entity)
		{
			this.SendPropertyChanging();
			entity.MILITARE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MISSIONE")]
	public partial class MISSIONE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Nome;
		
		private string _Descrizione;
		
		private System.Nullable<bool> _Emergenza;
		
		private string _Tipo;
		
		private string _CodiceAeroporto;
		
		private string _AeroportoDiPartenza;
		
		private string _AeroportoDiArrivo;
		
		private EntitySet<VOLO> _VOLO;
		
		private EntityRef<AEROPORTO> _AEROPORTO;
		
		private EntityRef<AEROPORTO> _AEROPORTO1;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnDescrizioneChanging(string value);
    partial void OnDescrizioneChanged();
    partial void OnEmergenzaChanging(System.Nullable<bool> value);
    partial void OnEmergenzaChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    partial void OnCodiceAeroportoChanging(string value);
    partial void OnCodiceAeroportoChanged();
    partial void OnAeroportoDiPartenzaChanging(string value);
    partial void OnAeroportoDiPartenzaChanged();
    partial void OnAeroportoDiArrivoChanging(string value);
    partial void OnAeroportoDiArrivoChanged();
    #endregion
		
		public MISSIONE()
		{
			this._VOLO = new EntitySet<VOLO>(new Action<VOLO>(this.attach_VOLO), new Action<VOLO>(this.detach_VOLO));
			this._AEROPORTO = default(EntityRef<AEROPORTO>);
			this._AEROPORTO1 = default(EntityRef<AEROPORTO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descrizione", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Descrizione
		{
			get
			{
				return this._Descrizione;
			}
			set
			{
				if ((this._Descrizione != value))
				{
					this.OnDescrizioneChanging(value);
					this.SendPropertyChanging();
					this._Descrizione = value;
					this.SendPropertyChanged("Descrizione");
					this.OnDescrizioneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emergenza", DbType="Bit")]
		public System.Nullable<bool> Emergenza
		{
			get
			{
				return this._Emergenza;
			}
			set
			{
				if ((this._Emergenza != value))
				{
					this.OnEmergenzaChanging(value);
					this.SendPropertyChanging();
					this._Emergenza = value;
					this.SendPropertyChanged("Emergenza");
					this.OnEmergenzaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceAeroporto", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string CodiceAeroporto
		{
			get
			{
				return this._CodiceAeroporto;
			}
			set
			{
				if ((this._CodiceAeroporto != value))
				{
					this.OnCodiceAeroportoChanging(value);
					this.SendPropertyChanging();
					this._CodiceAeroporto = value;
					this.SendPropertyChanged("CodiceAeroporto");
					this.OnCodiceAeroportoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AeroportoDiPartenza", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string AeroportoDiPartenza
		{
			get
			{
				return this._AeroportoDiPartenza;
			}
			set
			{
				if ((this._AeroportoDiPartenza != value))
				{
					if (this._AEROPORTO1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAeroportoDiPartenzaChanging(value);
					this.SendPropertyChanging();
					this._AeroportoDiPartenza = value;
					this.SendPropertyChanged("AeroportoDiPartenza");
					this.OnAeroportoDiPartenzaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AeroportoDiArrivo", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string AeroportoDiArrivo
		{
			get
			{
				return this._AeroportoDiArrivo;
			}
			set
			{
				if ((this._AeroportoDiArrivo != value))
				{
					if (this._AEROPORTO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAeroportoDiArrivoChanging(value);
					this.SendPropertyChanging();
					this._AeroportoDiArrivo = value;
					this.SendPropertyChanged("AeroportoDiArrivo");
					this.OnAeroportoDiArrivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MISSIONE_VOLO", Storage="_VOLO", ThisKey="Nome", OtherKey="Nome")]
		public EntitySet<VOLO> VOLO
		{
			get
			{
				return this._VOLO;
			}
			set
			{
				this._VOLO.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AEROPORTO_MISSIONE", Storage="_AEROPORTO", ThisKey="AeroportoDiArrivo", OtherKey="CodiceAeroporto", IsForeignKey=true)]
		public AEROPORTO AEROPORTO
		{
			get
			{
				return this._AEROPORTO.Entity;
			}
			set
			{
				AEROPORTO previousValue = this._AEROPORTO.Entity;
				if (((previousValue != value) 
							|| (this._AEROPORTO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AEROPORTO.Entity = null;
						previousValue.MISSIONE.Remove(this);
					}
					this._AEROPORTO.Entity = value;
					if ((value != null))
					{
						value.MISSIONE.Add(this);
						this._AeroportoDiArrivo = value.CodiceAeroporto;
					}
					else
					{
						this._AeroportoDiArrivo = default(string);
					}
					this.SendPropertyChanged("AEROPORTO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AEROPORTO_MISSIONE1", Storage="_AEROPORTO1", ThisKey="AeroportoDiPartenza", OtherKey="CodiceAeroporto", IsForeignKey=true)]
		public AEROPORTO AEROPORTO1
		{
			get
			{
				return this._AEROPORTO1.Entity;
			}
			set
			{
				AEROPORTO previousValue = this._AEROPORTO1.Entity;
				if (((previousValue != value) 
							|| (this._AEROPORTO1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AEROPORTO1.Entity = null;
						previousValue.MISSIONE1.Remove(this);
					}
					this._AEROPORTO1.Entity = value;
					if ((value != null))
					{
						value.MISSIONE1.Add(this);
						this._AeroportoDiPartenza = value.CodiceAeroporto;
					}
					else
					{
						this._AeroportoDiPartenza = default(string);
					}
					this.SendPropertyChanged("AEROPORTO1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VOLO(VOLO entity)
		{
			this.SendPropertyChanging();
			entity.MISSIONE = this;
		}
		
		private void detach_VOLO(VOLO entity)
		{
			this.SendPropertyChanging();
			entity.MISSIONE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PATENTE")]
	public partial class PATENTE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodiceAeromobile;
		
		private string _MatricolaMilitare;
		
		private System.DateTime _DataDiRilascio;
		
		private EntityRef<MILITARE> _MILITARE;
		
		private EntityRef<AEROMOBILE> _AEROMOBILE;
		
    #region Definizioni metodo Extensibility
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodiceAeromobileChanging(string value);
    partial void OnCodiceAeromobileChanged();
    partial void OnMatricolaMilitareChanging(string value);
    partial void OnMatricolaMilitareChanged();
    partial void OnDataDiRilascioChanging(System.DateTime value);
    partial void OnDataDiRilascioChanged();
    #endregion
		
		public PATENTE()
		{
			this._MILITARE = default(EntityRef<MILITARE>);
			this._AEROMOBILE = default(EntityRef<AEROMOBILE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodiceAeromobile", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodiceAeromobile
		{
			get
			{
				return this._CodiceAeromobile;
			}
			set
			{
				if ((this._CodiceAeromobile != value))
				{
					if (this._AEROMOBILE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodiceAeromobileChanging(value);
					this.SendPropertyChanging();
					this._CodiceAeromobile = value;
					this.SendPropertyChanged("CodiceAeromobile");
					this.OnCodiceAeromobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatricolaMilitare", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MatricolaMilitare
		{
			get
			{
				return this._MatricolaMilitare;
			}
			set
			{
				if ((this._MatricolaMilitare != value))
				{
					if (this._MILITARE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMatricolaMilitareChanging(value);
					this.SendPropertyChanging();
					this._MatricolaMilitare = value;
					this.SendPropertyChanged("MatricolaMilitare");
					this.OnMatricolaMilitareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataDiRilascio", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime DataDiRilascio
		{
			get
			{
				return this._DataDiRilascio;
			}
			set
			{
				if ((this._DataDiRilascio != value))
				{
					this.OnDataDiRilascioChanging(value);
					this.SendPropertyChanging();
					this._DataDiRilascio = value;
					this.SendPropertyChanged("DataDiRilascio");
					this.OnDataDiRilascioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MILITARE_PATENTE", Storage="_MILITARE", ThisKey="MatricolaMilitare", OtherKey="MatricolaMilitare", IsForeignKey=true)]
		public MILITARE MILITARE
		{
			get
			{
				return this._MILITARE.Entity;
			}
			set
			{
				MILITARE previousValue = this._MILITARE.Entity;
				if (((previousValue != value) 
							|| (this._MILITARE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MILITARE.Entity = null;
						previousValue.PATENTE.Remove(this);
					}
					this._MILITARE.Entity = value;
					if ((value != null))
					{
						value.PATENTE.Add(this);
						this._MatricolaMilitare = value.MatricolaMilitare;
					}
					else
					{
						this._MatricolaMilitare = default(string);
					}
					this.SendPropertyChanged("MILITARE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AEROMOBILE_PATENTE", Storage="_AEROMOBILE", ThisKey="CodiceAeromobile", OtherKey="CodiceAeromobile", IsForeignKey=true)]
		public AEROMOBILE AEROMOBILE
		{
			get
			{
				return this._AEROMOBILE.Entity;
			}
			set
			{
				AEROMOBILE previousValue = this._AEROMOBILE.Entity;
				if (((previousValue != value) 
							|| (this._AEROMOBILE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AEROMOBILE.Entity = null;
						previousValue.PATENTE.Remove(this);
					}
					this._AEROMOBILE.Entity = value;
					if ((value != null))
					{
						value.PATENTE.Add(this);
						this._CodiceAeromobile = value.CodiceAeromobile;
					}
					else
					{
						this._CodiceAeromobile = default(string);
					}
					this.SendPropertyChanged("AEROMOBILE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
